import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getProjectInfo } from "@/lib/headers";
import { ProjectProvider } from "@/lib/context/project";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { projectSubdomain, environment } = await getProjectInfo();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ProjectProvider projectSubdomain={projectSubdomain} environment={environment}>
          {children}
        </ProjectProvider>
      </body>
    </html>
  );
}
