import { Adapter } from "@/lib/Adapter.js";
import { DataModel } from "@/models/DataModel.js";
import { Account } from "@/models/Account.js";
import { Aggregation } from "@/models/Aggregation.js";
import { AuthProvider } from "@/models/AuthProvider.js";
import { Connector } from "@/models/Connector.js";
import { Job } from "@/models/Job.js";
import { Role } from "@/models/Role.js";
import { Media } from "@/models/Media.js";
import { MergeRequest } from "@/models/MergeRequest.js";
import { MergeRequestAction } from "@/models/MergeRequestAction.js";
import { TokenIssuer } from "@/models/TokenIssuer.js";
import { Invitation } from "@/models/Invitation.js";
import { Environment } from "@/models/Environment.js";
import { Secret } from "@/models/Secret.js";
import { Settings } from "@/models/Settings.js";
import { Snapshot } from "@/models/Snapshot.js";
import { Function } from "@/models/Function.js";
import { Event } from "@/models/Event.js";
import { EventSubscription } from "@/models/EventSubscription.js";

Adapter.registerModel(Account);
Adapter.registerModel(Aggregation);
Adapter.registerModel(AuthProvider);
Adapter.registerModel(Connector);
Adapter.registerModel(DataModel);
Adapter.registerModel(Environment);
Adapter.registerModel(Event);
Adapter.registerModel(EventSubscription);
Adapter.registerModel(Function);
Adapter.registerModel(Invitation);
Adapter.registerModel(Job);
Adapter.registerModel(Media);
Adapter.registerModel(MergeRequest);
Adapter.registerModel(MergeRequestAction);
Adapter.registerModel(Role);
Adapter.registerModel(Secret);
Adapter.registerModel(Settings);
Adapter.registerModel(Snapshot);
Adapter.registerModel(TokenIssuer);
