import { Adapter } from "@/lib/adapter.js";
import { DataModel } from "@/models/data-model.js";
import { Account } from "@/models/account.js";
import { Aggregation } from "@/models/aggregation.js";
import { AuthProvider } from "@/models/auth-provider.js";
import { Connector } from "@/models/connector.js";
import { Job } from "@/models/job.js";
import { Role } from "@/models/role.js";
import { Media } from "@/models/media.js";
import { MergeRequest } from "@/models/merge-request.js";
import { MergeRequestAction } from "@/models/merge-request-action.js";
import { TokenIssuer } from "@/models/token-issuer.js";
import { Invitation } from "@/models/invitation.js";
import { Environment } from "@/models/environment.js";
import { Secret } from "@/models/secret.js";
import { Settings } from "@/models/settings.js";
import { Snapshot } from "@/models/snapshot.js";
import { Function } from "@/models/function.js";
import { Event } from "@/models/event.js";
import { EventSubscription } from "@/models/event-subscription.js";

Adapter.registerModel(Account);
Adapter.registerModel(Aggregation);
Adapter.registerModel(AuthProvider);
Adapter.registerModel(Connector);
Adapter.registerModel(DataModel);
Adapter.registerModel(Environment);
Adapter.registerModel(Event);
Adapter.registerModel(EventSubscription);
Adapter.registerModel(Function);
Adapter.registerModel(Invitation);
Adapter.registerModel(Job);
Adapter.registerModel(Media);
Adapter.registerModel(MergeRequest);
Adapter.registerModel(MergeRequestAction);
Adapter.registerModel(Role);
Adapter.registerModel(Secret);
Adapter.registerModel(Settings);
Adapter.registerModel(Snapshot);
Adapter.registerModel(TokenIssuer);
