enum ErrorCodes {
  SOCKET_NOT_CONNECTED = "SOCKET_NOT_CONNECTED",
  CLIENT_NO_PROJECT = "CLIENT_NO_PROJECT",
  MODEL_NO_CLIENT = "MODEL_NO_CLIENT",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
}

export default ErrorCodes;
