export enum JobTypes {
  SYNC_CONNECTOR = "syncConnector",
  INIT_SNAPHSOT = "initSnapshot",
  INIT_ENVIRONMENT = "initEnvironment",
  INIT_MERGE_REQUEST = "initMergeRequest",
  APPROVE_MERGE_REQUEST = "approveMergeRequest",
  PATCH_MERGE_REQUEST = "patchMergeRequest",
  SANDBOX_MERGE_REQUEST = "sandboxMergeRequest",
  RESTORE_SNAPSHOT = "restoreSnapshot",
  INIT_PROJECT = "initProject",
  UPGRADE_PROJECT = "upgradeProject",
  RESTART_PROJECT = "restartProject",
  REMOVE_PROJECT = "removeProject",
  REMOVE_FUNCTION = "removeFunction",
  REMOVE_ENVIRONMENT = "removeEnvironment",
  DEPLOY_FUNCTION = "deployFunction",
  RUN_FUNCTION = "runFunction",
}
